In [ ]:
%whos

In [ ]:
score = input('점수: ')

In [ ]:
%whos

In [ ]:
score

In [ ]:
score = float(score)
score

In [ ]:
if score >= 90:
    print('합격')

In [ ]:
score = float(input('점수: '))
if score >= 90:
    print('합격')
elif score >= 80:
    print('재검사')
else:
    print('불합격')

In [ ]:
menu = ['짜장면', '탕수육', '깐풍기', '짬뽕', '전가복', '샥스핀']

In [ ]:
for item in menu:
    print('팀장님,', item, '시킬까요?')

In [ ]:
for item in menu:
    print('팀장님,', item, '시킬까요?')
    if item in ['짜장면', '짬뽕']:
        print('> 요리부터 주문합시다!')
    print('> 다음 메뉴는 뭔가요?\n')

In [ ]:
import random

In [ ]:
random.seed(1234)

In [ ]:
scores = random.sample(range(50, 100), 10)
scores

In [ ]:
# 비복원추출
random.sample(population = range(5), k = 5)

In [ ]:
# 복원추출
random.choices(population = range(5), k = 10)

In [ ]:
for score in scores:
    if score >= 90:
        print('합격')
    elif score >= 80:
        print('재검사')
    else:
        print('불합격')

In [ ]:
for item in menu:
    print('팀장님,', item, '시킬까요?')
    if item in ['짜장면', '짬뽕']:
        continue
    print('> 다음 메뉴는 뭔가요?\n')

In [ ]:
# Big Mark
num = 123456789
f'{num:,}'

In [ ]:
for item in menu:
    print('팀장님,', item, '시킬까요?')
    if item in ['전가복', '샥스핀']:
        break
    print('> 다음 메뉴는 뭔가요?\n')

In [ ]:
for i in range(2, 10):
    print(f'*** {i}단 ***')
    for j in range(1, 10):
        print(f'{i} * {j} = {i*j}')
    print()

In [ ]:
sqrs = []
for i in range(1, 11):
    sqrs.append(i ** 2)

In [ ]:
sqrs

In [ ]:
sqrs = []
for i in range(1, 11):
    if i % 2 == 0:
        sqrs.append(i ** 2)

In [ ]:
sqrs

In [ ]:
[i ** 2 for i in range(1, 11)]

In [ ]:
[i ** 2 for i in range(1, 11) if i % 2 == 0]

In [ ]:
[i ** 2 if i % 2 == 0 else i for i in range(1, 11)]

In [ ]:
for i, j in zip(range(2, 10), range(1, 10)):
    print(i, j)

In [ ]:
for i, v in enumerate(range(1, 11)):
    print(f'{i}번 인덱스 원소는 {v}입니다.')

In [ ]:
for i, v in enumerate(menu):
    print(f'{i}번 인덱스 메뉴는 {v}입니다.')

In [ ]:
for i in range(1, 11):
    if i % 3 == 0:
        i = str(i)
    print(i ** 2)

In [ ]:
for i in range(1, 11):
    if i % 3 == 0:
        i = str(i)
    try:
        print(i ** 2)
    except:
        print('에러 발생!')

In [ ]:
for i in range(1, 11):
    if i % 3 == 0:
        i = str(i)
    try:
        print(i ** 2)
    except Exception as e:
        print(e)

In [ ]:
i = 5

In [ ]:
while i > 0:
    print(i)
    i -= 1

In [ ]:
i

In [ ]:
while True:
    i += 1
    if i >= 10000:
        break

In [ ]:
i

In [ ]:
def BMI(hgt, wgt):
    bmi = wgt / (hgt/100)**2
    return bmi

In [ ]:
BMI(175, 65)

In [ ]:
BMI(65, 175)

In [ ]:
BMI(hgt = 175, wgt = 65)

In [ ]:
BMI(wgt = 65, hgt = 175)

In [ ]:
def BMI(hgt = 175, wgt = 65):
    '''
    이 함수는 키(cm)와 체중(kg)을 입력받아서 신체질량지수를 반환합니다.
    '''
    if type(hgt) != int:
        hgt = int(float(hgt))
    bmi = wgt / (hgt/100)**2
    return bmi

In [ ]:
BMI()

In [ ]:
BMI(hgt = '190.0', wgt = 95)

In [ ]:
hgt = 190

In [ ]:
type(hgt)

In [ ]:
type(hgt) != int

In [ ]:
import requests
from bs4 import BeautifulSoup as bts

In [ ]:
ticker = '005930'
url = f'https://finance.naver.com/item/main.naver?code={ticker}'
res = requests.get(url)
soup = bts(markup = res.text, features = 'html.parser')
items = soup.select('p.no_today > em > span')
price = items[0].text
price = int(price.replace(',', ''))
price

In [ ]:
# 종목코드 리스트로 생성
tickers = ['005930', '000660', '373220']

In [ ]:
import requests
from bs4 import BeautifulSoup as bts
import time

In [ ]:
for ticker in tickers:
    url = f'https://finance.naver.com/item/main.naver?code={ticker}'
    res = requests.get(url)
    soup = bts(markup = res.text, features = 'html.parser')
    items = soup.select('p.no_today > em > span')
    price = items[0].text
    price = int(price.replace(',', ''))
    print(f'{ticker}의 현재 가격은 {price}입니다.')
    time.sleep(1)

In [ ]:
def stockPrice(ticker):
    url = f'https://finance.naver.com/item/main.naver?code={ticker}'
    res = requests.get(url)
    soup = bts(markup = res.text, features = 'html.parser')
    items = soup.select('p.no_today > em > span')
    price = items[0].text
    price = int(price.replace(',', ''))
    return f'{ticker}의 현재 가격은 {price:,}원입니다.'

In [ ]:
for ticker in tickers:
    print(stockPrice(ticker = ticker))
    time.sleep(1)

In [ ]:
def BMI(hgt, wgt):
    bmi = wgt / (hgt/100)**2
    return bmi

In [ ]:
BMI2 = lambda hgt, wgt: wgt / (hgt/100)**2

In [ ]:
BMI2(175, 65)

In [ ]:
(lambda hgt, wgt: wgt / (hgt/100)**2)(175, 65)

In [ ]:
def printValues1(a, b, c):
    for i in (a, b, c):
        print(i)

In [ ]:
printValues1(1, 2, 3)

In [ ]:
printValues1(1, 2)

In [ ]:
def printValues2(*args):
    for i in args:
        print(i)

In [ ]:
printValues2(1, 2, 3)

In [ ]:
printValues2(1, 2)

In [ ]:
printValues2(a = 1, b = 2, c = 3)

In [ ]:
def printValues3(**kwargs):
    for k, v in kwargs.items():
        print(f'{k}은/는 {v}입니다.')

In [ ]:
printValues3(메뉴 = '순대국', 가격 = 9000)

In [ ]:
%whos

In [ ]:
import myFuncs

In [ ]:
%whos

In [ ]:
dir(myFuncs)

In [ ]:
myFuncs.stockPrice(ticker = '005930')

In [ ]:
import myFuncs as mf

In [ ]:
%whos

In [ ]:
mf.stockPrice(ticker = '005930')

In [ ]:
dir(mf)

In [ ]:
from myFuncs import stockPrice

In [ ]:
%whos

In [ ]:
stockPrice(ticker = '005930')

In [ ]:
import requests
from bs4 import BeautifulSoup as bts

In [ ]:
url = 'https://finance.naver.com/sise/sise_market_sum.naver'

In [ ]:
res = requests.get(url)

In [ ]:
soup = bts(markup = res.text, features = 'html.parser')

In [ ]:
items = soup.select('a.tltle')

In [ ]:
items[0].text

In [ ]:
items[0]['href']

In [ ]:
items[0]['href'].replace('/item/main.naver?code=', '')

In [ ]:
tickers = [item['href'].replace('/item/main.naver?code=', '') for item in items]

In [ ]:
import time

for ticker in tickers:
    print(stockPrice(ticker = ticker))
    time.sleep(1)

In [ ]:
a = [1, 2, 3]

In [ ]:
a

In [ ]:
import numpy as np

In [ ]:
ar1 = np.array([1, 2, 3])
ar1

In [ ]:
print(ar1)

In [ ]:
print([1, 2, 3])

In [ ]:
type(ar1)

In [ ]:
[1, 2, 3] + [1, 2, 3]

In [ ]:
ar1 + ar1

In [ ]:
dir(ar1)

In [ ]:
ar1.shape

In [ ]:
ar1.size

In [ ]:
ar1.dtype

In [ ]:
a = [1, 2.0, '3']

In [ ]:
ar1 = np.array(a)
ar1

In [ ]:
ar1.astype(float)

In [ ]:
ar1.astype(int)

In [ ]:
# method chaining
ar1.astype(float).astype(int)

In [ ]:
ar1.astype(float) \
   .astype(int)

In [ ]:
np.array(a, dtype = float)

In [ ]:
np.array(a, dtype = int)

In [ ]:
np.array(a, dtype = str)

In [ ]:
np.array(a, dtype = object)

In [ ]:
list(range(5))

In [ ]:
list(range(1, 6))

In [ ]:
list(range(1,11, 2))

In [ ]:
list(range(0, 1, 0.1))

In [ ]:
np.arange(5)

In [ ]:
np.arange(1, 6)

In [ ]:
np.arange(1, 11, 2)

In [ ]:
np.arange(0, 1.1, 0.1)

In [ ]:
np.linspace(0, 1, 10+1)

In [ ]:
%precision 2

In [ ]:
np.linspace(80, 75, 30+1)

In [ ]:
%precision 4

In [ ]:
np.round(np.linspace(80, 75, 30+1), 2)

In [ ]:
np.tile(ar1, 2)

In [ ]:
np.repeat(ar1, 2)

In [ ]:
np.repeat(ar1, [3, 2, 1])

In [ ]:
np.repeat(ar1, range(3, 0, -1))

In [ ]:
myPal = np.tile('gray', 25)

In [ ]:
myPal[1] = 'red'

In [ ]:
myPal

In [ ]:
ar1 = np.arange(1, 12, 2)
ar1

In [ ]:
ar1[0]

In [ ]:
ar1[1]

In [ ]:
ar1[-1]

In [ ]:
ar1[:3]

In [ ]:
ar1[3:]

In [ ]:
ar1[:]

In [ ]:
a[[1, 2]]

In [ ]:
ar1[[3, 2, 1]]

In [ ]:
ar1[[3, 3, 3]]

In [ ]:
ar1[np.arange(3, 0, -1)]

In [ ]:
ar1[np.tile(3, 3)]

In [ ]:
ar2 = np.array([[1, 2, 3], [4, 5, 6]])
ar2

In [ ]:
type(ar2)

In [ ]:
ar2.shape

In [ ]:
ar2.size

In [ ]:
ar2.dtype

In [ ]:
ar1 = np.arange(12)
ar1

In [ ]:
ar1.reshape(4, 3, order = 'C')

In [ ]:
ar1.reshape(4, 3, order = 'F')

In [ ]:
ar2 = ar1.reshape(4, -1)
ar2

In [ ]:
ar2.flatten()

In [ ]:
ar2

In [ ]:
ar2[0, 0]

In [ ]:
ar2[1, 1]

In [ ]:
ar2[0:2, 0:2]

In [ ]:
ar2[:, 1:3]

In [ ]:
ar2[:, [2, 1]]

In [ ]:
ar2.flatten().reshape(-1, 1)

In [ ]:
ar1 = np.arange(3)
ar1

In [ ]:
ar2 = ar1.reshape(-1, 1)
ar2

In [ ]:
ar1 + 1

In [ ]:
a = [1, 2, 3]

In [ ]:
[i + 1 for i in a]

In [ ]:
ar2 * 2

In [ ]:
ar1 + ar2

In [1]:
import numpy as np
import pandas as pd

In [2]:
ar1 = np.arange(1, 6, 2)
ar1

array([1, 3, 5])

In [3]:
sr = pd.Series(ar1)
sr

0    1
1    3
2    5
dtype: int32

In [4]:
type(sr)

pandas.core.series.Series

In [5]:
sr1 = pd.Series(data = [1, 2.0, '3'], index = ['a', 'b', 'c'])
sr1

a      1
b    2.0
c      3
dtype: object

In [6]:
for i in sr1:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>


In [9]:
sr1.astype(str) + '등'

a      1등
b    2.0등
c      3등
dtype: object

In [10]:
sr1.astype(float) + 1

a    2.0
b    3.0
c    4.0
dtype: float64

In [11]:
sr

0    1
1    3
2    5
dtype: int32

In [12]:
sr.shape

(3,)

In [13]:
sr.size

3

In [14]:
sr.dtype

dtype('int32')

In [15]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [16]:
sr.values

array([1, 3, 5])

In [17]:
sr.index

RangeIndex(start=0, stop=3, step=1)

In [18]:
type(sr.index)

pandas.core.indexes.range.RangeIndex

In [19]:
sr.index = [1, 2, 3]
sr

1    1
2    3
3    5
dtype: int32

In [20]:
type(sr.index)

pandas.core.indexes.numeric.Int64Index

In [21]:
sr.index = ['a', 'b', 'c']
sr

a    1
b    3
c    5
dtype: int32

In [22]:
type(sr.index)

pandas.core.indexes.base.Index

In [24]:
sr1.index = [1, 1, 1]
sr1

1      1
1    2.0
1      3
dtype: object

In [25]:
sr

a    1
b    3
c    5
dtype: int32

In [30]:
sr.iloc[0]

1

In [31]:
sr.iloc[[0]]

a    1
dtype: int32

In [32]:
sr.iloc[[0, 2]]

a    1
c    5
dtype: int32

In [33]:
sr.iloc[0:2]

a    1
b    3
dtype: int32

In [34]:
sr

a    1
b    3
c    5
dtype: int32

In [35]:
sr.loc['a']

1

In [36]:
sr.loc[['a']]

a    1
dtype: int32

In [37]:
sr.loc[['a', 'c']]

a    1
c    5
dtype: int32

In [38]:
sr.loc['a':'c']

a    1
b    3
c    5
dtype: int32

In [39]:
sr2 = pd.Series(data = range(3), index = range(1, 4))
sr2

1    0
2    1
3    2
dtype: int64

In [40]:
sr2[0]

KeyError: 0

In [41]:
sr2.iloc[0]

0

In [42]:
sr3 = pd.Series(data = range(3), index = np.tile(1, 3))
sr3

1    0
1    1
1    2
dtype: int64

In [43]:
sr3.loc[1]

1    0
1    1
1    2
dtype: int64

In [44]:
sr3.iloc[0]

0

In [45]:
sr

a    1
b    3
c    5
dtype: int32

In [46]:
sr >= 3

a    False
b     True
c     True
dtype: bool

In [47]:
sr.loc[sr >= 3]

b    3
c    5
dtype: int32

In [48]:
sr.iloc[sr >= 3]

ValueError: iLocation based boolean indexing cannot use an indexable as a mask

In [49]:
sr.loc[sr >= 3 and sr < 5]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [52]:
sr.iloc[0] >= 3

False

In [53]:
sr.iloc[0] >= 3 and sr.iloc[0] < 5

False

In [54]:
sr >= 3

a    False
b     True
c     True
dtype: bool

In [55]:
sr < 5

a     True
b     True
c    False
dtype: bool

In [56]:
(sr >= 3) & (sr < 5)

a    False
b     True
c    False
dtype: bool

In [57]:
sr[(sr >= 3) & (sr < 5)]

b    3
dtype: int32

In [58]:
(sr >= 3) | (sr < 5)

a    True
b    True
c    True
dtype: bool

In [59]:
(sr >= 3) ^ (sr < 5)

a     True
b    False
c     True
dtype: bool

In [60]:
(sr >= 3)

a    False
b     True
c     True
dtype: bool

In [61]:
~ (sr >= 3)

a     True
b    False
c    False
dtype: bool

In [62]:
sr4 = sr1
sr4

1      1
1    2.0
1      3
dtype: object

In [63]:
id(sr1)

2260643064960

In [64]:
id(sr4)

2260643064960

In [65]:
sr4.iloc[0] = 2

In [66]:
sr4

1      2
1    2.0
1      3
dtype: object

In [67]:
sr1

1      2
1    2.0
1      3
dtype: object

In [68]:
sr5 = sr1.copy()

In [69]:
id(sr5)

2261004376656

In [70]:
id(sr1)

2260643064960

In [71]:
sr5.iloc[0] = 1

In [72]:
sr5

1      1
1    2.0
1      3
dtype: object

In [73]:
sr1

1      2
1    2.0
1      3
dtype: object

In [74]:
ar2 = np.arange(1, 7).reshape(3, -1)
ar2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
df = pd.DataFrame(ar2)
df

0  1
0  1  2
1  3  4
2  5  6

In [76]:
type(df)

pandas.core.frame.DataFrame

In [77]:
df = pd.DataFrame(ar2, index = range(1, 4), columns = ['A', 'B'])
df

A  B
1  1  2
2  3  4
3  5  6

In [78]:
df.shape

(3, 2)

In [79]:
df.dtypes

A    int32
B    int32
dtype: object

In [80]:
df.values

array([[1, 2],
       [3, 4],
       [5, 6]])

In [81]:
df.index

RangeIndex(start=1, stop=4, step=1)

In [82]:
df.columns

Index(['A', 'B'], dtype='object')

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 1 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int32
 1   B       3 non-null      int32
dtypes: int32(2)
memory usage: 156.0 bytes


In [84]:
df

A  B
1  1  2
2  3  4
3  5  6

In [85]:
df.iloc[0]

A    1
B    2
Name: 1, dtype: int32

In [86]:
df.iloc[[0]]

A  B
1  1  2

In [87]:
df.iloc[0:2]

A  B
1  1  2
2  3  4

In [88]:
df.iloc[0:2, :]

A  B
1  1  2
2  3  4

In [89]:
df.iloc[0:2, 0:2]

A  B
1  1  2
2  3  4

In [90]:
df.iloc[:, [1, 0]]

B  A
1  2  1
2  4  3
3  6  5

In [91]:
df

A  B
1  1  2
2  3  4
3  5  6

In [92]:
df.loc[1]

A    1
B    2
Name: 1, dtype: int32

In [93]:
df.loc[[1]]

A  B
1  1  2

In [94]:
df.loc[1:3]

A  B
1  1  2
2  3  4
3  5  6

In [95]:
df.loc[1:3, :]

A  B
1  1  2
2  3  4
3  5  6

In [97]:
df.loc[1:2, 'A':'B']

A  B
1  1  2
2  3  4

In [98]:
df.loc[:, ['B', 'A']]

B  A
1  2  1
2  4  3
3  6  5